name: PR Validation

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "cookiecutter.json"
      - "{{cookiecutter.project_slug}}/**"
      - "hooks/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full cmake ninja-build libx11-dev libdbus-1-dev uuid-dev libgl1-mesa-dev
          pip install cookiecutter

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          pip install cookiecutter
          choco install 7zip

      - name: Generate project (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cookiecutter . --no-input \
            rbfx_sdk_install="dll" \
            project_name="PR Test" \
            project_slug="pr_test"

      - name: Generate project (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          cookiecutter . --no-input rbfx_sdk_install="dll" project_name="PR Test" project_slug="pr_test" editor=n

      - name: Configure and build (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cmake -S pr_test -B pr_test/build \
            -G Ninja \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_PREFIX_PATH=../rbfx
          cmake --build pr_test/build

      - name: Configure and build (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          cmake -S pr_test -B pr_test/build -DBUILD_SHARED_LIBS=ON "-DCMAKE_PREFIX_PATH=../rbfx"
          cmake --build pr_test/build --config RelWithDebInfo
